package com.liangbo.xing.flexibletranscation.mapper;

import com.liangbo.xing.flexibletranscation.domain.ftm.AppDo;
import com.liangbo.xing.flexibletranscation.domain.ftm.AppDoExample;
import java.util.List;

public interface AppDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    int insert(AppDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    int insertSelective(AppDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    List<AppDo> selectByExample(AppDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    AppDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    int updateByPrimaryKeySelective(AppDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    int updateByPrimaryKey(AppDo record);
}