package com.liangbo.xing.flexibletranscation.mapper;

import com.liangbo.xing.flexibletranscation.domain.ftm.TopicDo;
import com.liangbo.xing.flexibletranscation.domain.ftm.TopicDoExample;
import java.util.List;

public interface TopicDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    int insert(TopicDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    int insertSelective(TopicDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    List<TopicDo> selectByExample(TopicDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    TopicDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    int updateByPrimaryKeySelective(TopicDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    int updateByPrimaryKey(TopicDo record);
}