package com.liangbo.xing.flexibletranscation.mapper;

import com.liangbo.xing.flexibletranscation.domain.ftm.TopicSubDo;
import com.liangbo.xing.flexibletranscation.domain.ftm.TopicSubDoExample;
import java.util.List;

public interface TopicSubDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic_sub
     *
     * @mbggenerated Sun Dec 24 19:13:05 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic_sub
     *
     * @mbggenerated Sun Dec 24 19:13:05 CST 2017
     */
    int insert(TopicSubDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic_sub
     *
     * @mbggenerated Sun Dec 24 19:13:05 CST 2017
     */
    int insertSelective(TopicSubDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic_sub
     *
     * @mbggenerated Sun Dec 24 19:13:05 CST 2017
     */
    List<TopicSubDo> selectByExample(TopicSubDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic_sub
     *
     * @mbggenerated Sun Dec 24 19:13:05 CST 2017
     */
    TopicSubDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic_sub
     *
     * @mbggenerated Sun Dec 24 19:13:05 CST 2017
     */
    int updateByPrimaryKeySelective(TopicSubDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic_sub
     *
     * @mbggenerated Sun Dec 24 19:13:05 CST 2017
     */
    int updateByPrimaryKey(TopicSubDo record);
}