package com.liangbo.xing.flexibletranscation.domain.ftm;

import java.util.Date;

public class AppDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.id
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.appId
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.appName
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    private String appname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.appDesc
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    private String appdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.createTime
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.updateTime
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.appKey
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    private String appkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.callBackUrl
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    private String callbackurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.id
     *
     * @return the value of t_app.id
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.id
     *
     * @param id the value for t_app.id
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.appId
     *
     * @return the value of t_app.appId
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.appId
     *
     * @param appid the value for t_app.appId
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.appName
     *
     * @return the value of t_app.appName
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    public String getAppname() {
        return appname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.appName
     *
     * @param appname the value for t_app.appName
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    public void setAppname(String appname) {
        this.appname = appname == null ? null : appname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.appDesc
     *
     * @return the value of t_app.appDesc
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    public String getAppdesc() {
        return appdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.appDesc
     *
     * @param appdesc the value for t_app.appDesc
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    public void setAppdesc(String appdesc) {
        this.appdesc = appdesc == null ? null : appdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.createTime
     *
     * @return the value of t_app.createTime
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.createTime
     *
     * @param createtime the value for t_app.createTime
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.updateTime
     *
     * @return the value of t_app.updateTime
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.updateTime
     *
     * @param updatetime the value for t_app.updateTime
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.appKey
     *
     * @return the value of t_app.appKey
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    public String getAppkey() {
        return appkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.appKey
     *
     * @param appkey the value for t_app.appKey
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    public void setAppkey(String appkey) {
        this.appkey = appkey == null ? null : appkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.callBackUrl
     *
     * @return the value of t_app.callBackUrl
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    public String getCallbackurl() {
        return callbackurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.callBackUrl
     *
     * @param callbackurl the value for t_app.callBackUrl
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    public void setCallbackurl(String callbackurl) {
        this.callbackurl = callbackurl == null ? null : callbackurl.trim();
    }
}