package com.liangbo.xing.flexibletranscation.domain.ftm;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TopicDoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_topic
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_topic
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_topic
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    public TopicDoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_topic
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_topic
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTopicIsNull() {
            addCriterion("topic is null");
            return (Criteria) this;
        }

        public Criteria andTopicIsNotNull() {
            addCriterion("topic is not null");
            return (Criteria) this;
        }

        public Criteria andTopicEqualTo(String value) {
            addCriterion("topic =", value, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicNotEqualTo(String value) {
            addCriterion("topic <>", value, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicGreaterThan(String value) {
            addCriterion("topic >", value, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicGreaterThanOrEqualTo(String value) {
            addCriterion("topic >=", value, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicLessThan(String value) {
            addCriterion("topic <", value, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicLessThanOrEqualTo(String value) {
            addCriterion("topic <=", value, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicLike(String value) {
            addCriterion("topic like", value, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicNotLike(String value) {
            addCriterion("topic not like", value, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicIn(List<String> values) {
            addCriterion("topic in", values, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicNotIn(List<String> values) {
            addCriterion("topic not in", values, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicBetween(String value1, String value2) {
            addCriterion("topic between", value1, value2, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicNotBetween(String value1, String value2) {
            addCriterion("topic not between", value1, value2, "topic");
            return (Criteria) this;
        }

        public Criteria andTopicidIsNull() {
            addCriterion("topicId is null");
            return (Criteria) this;
        }

        public Criteria andTopicidIsNotNull() {
            addCriterion("topicId is not null");
            return (Criteria) this;
        }

        public Criteria andTopicidEqualTo(String value) {
            addCriterion("topicId =", value, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidNotEqualTo(String value) {
            addCriterion("topicId <>", value, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidGreaterThan(String value) {
            addCriterion("topicId >", value, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidGreaterThanOrEqualTo(String value) {
            addCriterion("topicId >=", value, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidLessThan(String value) {
            addCriterion("topicId <", value, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidLessThanOrEqualTo(String value) {
            addCriterion("topicId <=", value, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidLike(String value) {
            addCriterion("topicId like", value, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidNotLike(String value) {
            addCriterion("topicId not like", value, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidIn(List<String> values) {
            addCriterion("topicId in", values, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidNotIn(List<String> values) {
            addCriterion("topicId not in", values, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidBetween(String value1, String value2) {
            addCriterion("topicId between", value1, value2, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidNotBetween(String value1, String value2) {
            addCriterion("topicId not between", value1, value2, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicdescIsNull() {
            addCriterion("topicDesc is null");
            return (Criteria) this;
        }

        public Criteria andTopicdescIsNotNull() {
            addCriterion("topicDesc is not null");
            return (Criteria) this;
        }

        public Criteria andTopicdescEqualTo(String value) {
            addCriterion("topicDesc =", value, "topicdesc");
            return (Criteria) this;
        }

        public Criteria andTopicdescNotEqualTo(String value) {
            addCriterion("topicDesc <>", value, "topicdesc");
            return (Criteria) this;
        }

        public Criteria andTopicdescGreaterThan(String value) {
            addCriterion("topicDesc >", value, "topicdesc");
            return (Criteria) this;
        }

        public Criteria andTopicdescGreaterThanOrEqualTo(String value) {
            addCriterion("topicDesc >=", value, "topicdesc");
            return (Criteria) this;
        }

        public Criteria andTopicdescLessThan(String value) {
            addCriterion("topicDesc <", value, "topicdesc");
            return (Criteria) this;
        }

        public Criteria andTopicdescLessThanOrEqualTo(String value) {
            addCriterion("topicDesc <=", value, "topicdesc");
            return (Criteria) this;
        }

        public Criteria andTopicdescLike(String value) {
            addCriterion("topicDesc like", value, "topicdesc");
            return (Criteria) this;
        }

        public Criteria andTopicdescNotLike(String value) {
            addCriterion("topicDesc not like", value, "topicdesc");
            return (Criteria) this;
        }

        public Criteria andTopicdescIn(List<String> values) {
            addCriterion("topicDesc in", values, "topicdesc");
            return (Criteria) this;
        }

        public Criteria andTopicdescNotIn(List<String> values) {
            addCriterion("topicDesc not in", values, "topicdesc");
            return (Criteria) this;
        }

        public Criteria andTopicdescBetween(String value1, String value2) {
            addCriterion("topicDesc between", value1, value2, "topicdesc");
            return (Criteria) this;
        }

        public Criteria andTopicdescNotBetween(String value1, String value2) {
            addCriterion("topicDesc not between", value1, value2, "topicdesc");
            return (Criteria) this;
        }

        public Criteria andTableindexIsNull() {
            addCriterion("tableIndex is null");
            return (Criteria) this;
        }

        public Criteria andTableindexIsNotNull() {
            addCriterion("tableIndex is not null");
            return (Criteria) this;
        }

        public Criteria andTableindexEqualTo(Integer value) {
            addCriterion("tableIndex =", value, "tableindex");
            return (Criteria) this;
        }

        public Criteria andTableindexNotEqualTo(Integer value) {
            addCriterion("tableIndex <>", value, "tableindex");
            return (Criteria) this;
        }

        public Criteria andTableindexGreaterThan(Integer value) {
            addCriterion("tableIndex >", value, "tableindex");
            return (Criteria) this;
        }

        public Criteria andTableindexGreaterThanOrEqualTo(Integer value) {
            addCriterion("tableIndex >=", value, "tableindex");
            return (Criteria) this;
        }

        public Criteria andTableindexLessThan(Integer value) {
            addCriterion("tableIndex <", value, "tableindex");
            return (Criteria) this;
        }

        public Criteria andTableindexLessThanOrEqualTo(Integer value) {
            addCriterion("tableIndex <=", value, "tableindex");
            return (Criteria) this;
        }

        public Criteria andTableindexIn(List<Integer> values) {
            addCriterion("tableIndex in", values, "tableindex");
            return (Criteria) this;
        }

        public Criteria andTableindexNotIn(List<Integer> values) {
            addCriterion("tableIndex not in", values, "tableindex");
            return (Criteria) this;
        }

        public Criteria andTableindexBetween(Integer value1, Integer value2) {
            addCriterion("tableIndex between", value1, value2, "tableindex");
            return (Criteria) this;
        }

        public Criteria andTableindexNotBetween(Integer value1, Integer value2) {
            addCriterion("tableIndex not between", value1, value2, "tableindex");
            return (Criteria) this;
        }

        public Criteria andMaxretrytimeIsNull() {
            addCriterion("maxRetryTime is null");
            return (Criteria) this;
        }

        public Criteria andMaxretrytimeIsNotNull() {
            addCriterion("maxRetryTime is not null");
            return (Criteria) this;
        }

        public Criteria andMaxretrytimeEqualTo(Integer value) {
            addCriterion("maxRetryTime =", value, "maxretrytime");
            return (Criteria) this;
        }

        public Criteria andMaxretrytimeNotEqualTo(Integer value) {
            addCriterion("maxRetryTime <>", value, "maxretrytime");
            return (Criteria) this;
        }

        public Criteria andMaxretrytimeGreaterThan(Integer value) {
            addCriterion("maxRetryTime >", value, "maxretrytime");
            return (Criteria) this;
        }

        public Criteria andMaxretrytimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("maxRetryTime >=", value, "maxretrytime");
            return (Criteria) this;
        }

        public Criteria andMaxretrytimeLessThan(Integer value) {
            addCriterion("maxRetryTime <", value, "maxretrytime");
            return (Criteria) this;
        }

        public Criteria andMaxretrytimeLessThanOrEqualTo(Integer value) {
            addCriterion("maxRetryTime <=", value, "maxretrytime");
            return (Criteria) this;
        }

        public Criteria andMaxretrytimeIn(List<Integer> values) {
            addCriterion("maxRetryTime in", values, "maxretrytime");
            return (Criteria) this;
        }

        public Criteria andMaxretrytimeNotIn(List<Integer> values) {
            addCriterion("maxRetryTime not in", values, "maxretrytime");
            return (Criteria) this;
        }

        public Criteria andMaxretrytimeBetween(Integer value1, Integer value2) {
            addCriterion("maxRetryTime between", value1, value2, "maxretrytime");
            return (Criteria) this;
        }

        public Criteria andMaxretrytimeNotBetween(Integer value1, Integer value2) {
            addCriterion("maxRetryTime not between", value1, value2, "maxretrytime");
            return (Criteria) this;
        }

        public Criteria andRetryintervalIsNull() {
            addCriterion("retryInterval is null");
            return (Criteria) this;
        }

        public Criteria andRetryintervalIsNotNull() {
            addCriterion("retryInterval is not null");
            return (Criteria) this;
        }

        public Criteria andRetryintervalEqualTo(Integer value) {
            addCriterion("retryInterval =", value, "retryinterval");
            return (Criteria) this;
        }

        public Criteria andRetryintervalNotEqualTo(Integer value) {
            addCriterion("retryInterval <>", value, "retryinterval");
            return (Criteria) this;
        }

        public Criteria andRetryintervalGreaterThan(Integer value) {
            addCriterion("retryInterval >", value, "retryinterval");
            return (Criteria) this;
        }

        public Criteria andRetryintervalGreaterThanOrEqualTo(Integer value) {
            addCriterion("retryInterval >=", value, "retryinterval");
            return (Criteria) this;
        }

        public Criteria andRetryintervalLessThan(Integer value) {
            addCriterion("retryInterval <", value, "retryinterval");
            return (Criteria) this;
        }

        public Criteria andRetryintervalLessThanOrEqualTo(Integer value) {
            addCriterion("retryInterval <=", value, "retryinterval");
            return (Criteria) this;
        }

        public Criteria andRetryintervalIn(List<Integer> values) {
            addCriterion("retryInterval in", values, "retryinterval");
            return (Criteria) this;
        }

        public Criteria andRetryintervalNotIn(List<Integer> values) {
            addCriterion("retryInterval not in", values, "retryinterval");
            return (Criteria) this;
        }

        public Criteria andRetryintervalBetween(Integer value1, Integer value2) {
            addCriterion("retryInterval between", value1, value2, "retryinterval");
            return (Criteria) this;
        }

        public Criteria andRetryintervalNotBetween(Integer value1, Integer value2) {
            addCriterion("retryInterval not between", value1, value2, "retryinterval");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_topic
     *
     * @mbggenerated do_not_delete_during_merge Sat Dec 23 23:04:26 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_topic
     *
     * @mbggenerated Sat Dec 23 23:04:26 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}