package com.liangbo.xing.flexibletranscation.domain.ftm;

import java.util.Date;

public class TopicSubDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_topic_sub.id
     *
     * @mbggenerated Sun Dec 24 19:13:05 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_topic_sub.topicId
     *
     * @mbggenerated Sun Dec 24 19:13:05 CST 2017
     */
    private String topicid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_topic_sub.subId
     *
     * @mbggenerated Sun Dec 24 19:13:05 CST 2017
     */
    private String subid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_topic_sub.createTime
     *
     * @mbggenerated Sun Dec 24 19:13:05 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_topic_sub.updateTime
     *
     * @mbggenerated Sun Dec 24 19:13:05 CST 2017
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_topic_sub.rountingKey
     *
     * @mbggenerated Sun Dec 24 19:13:05 CST 2017
     */
    private String rountingkey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_topic_sub.id
     *
     * @return the value of t_topic_sub.id
     *
     * @mbggenerated Sun Dec 24 19:13:05 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_topic_sub.id
     *
     * @param id the value for t_topic_sub.id
     *
     * @mbggenerated Sun Dec 24 19:13:05 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_topic_sub.topicId
     *
     * @return the value of t_topic_sub.topicId
     *
     * @mbggenerated Sun Dec 24 19:13:05 CST 2017
     */
    public String getTopicid() {
        return topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_topic_sub.topicId
     *
     * @param topicid the value for t_topic_sub.topicId
     *
     * @mbggenerated Sun Dec 24 19:13:05 CST 2017
     */
    public void setTopicid(String topicid) {
        this.topicid = topicid == null ? null : topicid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_topic_sub.subId
     *
     * @return the value of t_topic_sub.subId
     *
     * @mbggenerated Sun Dec 24 19:13:05 CST 2017
     */
    public String getSubid() {
        return subid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_topic_sub.subId
     *
     * @param subid the value for t_topic_sub.subId
     *
     * @mbggenerated Sun Dec 24 19:13:05 CST 2017
     */
    public void setSubid(String subid) {
        this.subid = subid == null ? null : subid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_topic_sub.createTime
     *
     * @return the value of t_topic_sub.createTime
     *
     * @mbggenerated Sun Dec 24 19:13:05 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_topic_sub.createTime
     *
     * @param createtime the value for t_topic_sub.createTime
     *
     * @mbggenerated Sun Dec 24 19:13:05 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_topic_sub.updateTime
     *
     * @return the value of t_topic_sub.updateTime
     *
     * @mbggenerated Sun Dec 24 19:13:05 CST 2017
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_topic_sub.updateTime
     *
     * @param updatetime the value for t_topic_sub.updateTime
     *
     * @mbggenerated Sun Dec 24 19:13:05 CST 2017
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_topic_sub.rountingKey
     *
     * @return the value of t_topic_sub.rountingKey
     *
     * @mbggenerated Sun Dec 24 19:13:05 CST 2017
     */
    public String getRountingkey() {
        return rountingkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_topic_sub.rountingKey
     *
     * @param rountingkey the value for t_topic_sub.rountingKey
     *
     * @mbggenerated Sun Dec 24 19:13:05 CST 2017
     */
    public void setRountingkey(String rountingkey) {
        this.rountingkey = rountingkey == null ? null : rountingkey.trim();
    }
}