package com.liangbo.xing.flexibletranscation.domain.ftm;

import java.util.Date;

public class TranscationMsgSubDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transcation_msg_sub.id
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transcation_msg_sub.messageId
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    private String messageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transcation_msg_sub.status
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transcation_msg_sub.topicId
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    private String topicid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transcation_msg_sub.subId
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    private String subid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transcation_msg_sub.maxRetry
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    private Integer maxretry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transcation_msg_sub.retryInterval
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    private Integer retryinterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transcation_msg_sub.retry
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    private Integer retry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transcation_msg_sub.nextRetryTime
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    private Date nextretrytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transcation_msg_sub.version
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transcation_msg_sub.createTime
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transcation_msg_sub.updateTime
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transcation_msg_sub.id
     *
     * @return the value of t_transcation_msg_sub.id
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transcation_msg_sub.id
     *
     * @param id the value for t_transcation_msg_sub.id
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transcation_msg_sub.messageId
     *
     * @return the value of t_transcation_msg_sub.messageId
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public String getMessageid() {
        return messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transcation_msg_sub.messageId
     *
     * @param messageid the value for t_transcation_msg_sub.messageId
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void setMessageid(String messageid) {
        this.messageid = messageid == null ? null : messageid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transcation_msg_sub.status
     *
     * @return the value of t_transcation_msg_sub.status
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transcation_msg_sub.status
     *
     * @param status the value for t_transcation_msg_sub.status
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transcation_msg_sub.topicId
     *
     * @return the value of t_transcation_msg_sub.topicId
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public String getTopicid() {
        return topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transcation_msg_sub.topicId
     *
     * @param topicid the value for t_transcation_msg_sub.topicId
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void setTopicid(String topicid) {
        this.topicid = topicid == null ? null : topicid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transcation_msg_sub.subId
     *
     * @return the value of t_transcation_msg_sub.subId
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public String getSubid() {
        return subid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transcation_msg_sub.subId
     *
     * @param subid the value for t_transcation_msg_sub.subId
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void setSubid(String subid) {
        this.subid = subid == null ? null : subid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transcation_msg_sub.maxRetry
     *
     * @return the value of t_transcation_msg_sub.maxRetry
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public Integer getMaxretry() {
        return maxretry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transcation_msg_sub.maxRetry
     *
     * @param maxretry the value for t_transcation_msg_sub.maxRetry
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void setMaxretry(Integer maxretry) {
        this.maxretry = maxretry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transcation_msg_sub.retryInterval
     *
     * @return the value of t_transcation_msg_sub.retryInterval
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public Integer getRetryinterval() {
        return retryinterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transcation_msg_sub.retryInterval
     *
     * @param retryinterval the value for t_transcation_msg_sub.retryInterval
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void setRetryinterval(Integer retryinterval) {
        this.retryinterval = retryinterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transcation_msg_sub.retry
     *
     * @return the value of t_transcation_msg_sub.retry
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public Integer getRetry() {
        return retry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transcation_msg_sub.retry
     *
     * @param retry the value for t_transcation_msg_sub.retry
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void setRetry(Integer retry) {
        this.retry = retry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transcation_msg_sub.nextRetryTime
     *
     * @return the value of t_transcation_msg_sub.nextRetryTime
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public Date getNextretrytime() {
        return nextretrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transcation_msg_sub.nextRetryTime
     *
     * @param nextretrytime the value for t_transcation_msg_sub.nextRetryTime
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void setNextretrytime(Date nextretrytime) {
        this.nextretrytime = nextretrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transcation_msg_sub.version
     *
     * @return the value of t_transcation_msg_sub.version
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transcation_msg_sub.version
     *
     * @param version the value for t_transcation_msg_sub.version
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transcation_msg_sub.createTime
     *
     * @return the value of t_transcation_msg_sub.createTime
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transcation_msg_sub.createTime
     *
     * @param createtime the value for t_transcation_msg_sub.createTime
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transcation_msg_sub.updateTime
     *
     * @return the value of t_transcation_msg_sub.updateTime
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transcation_msg_sub.updateTime
     *
     * @param updatetime the value for t_transcation_msg_sub.updateTime
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}