package com.liangbo.xing.flexibletranscation.domain.ftm;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TranscationMsgSubDoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_transcation_msg_sub
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_transcation_msg_sub
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_transcation_msg_sub
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transcation_msg_sub
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public TranscationMsgSubDoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transcation_msg_sub
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transcation_msg_sub
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transcation_msg_sub
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transcation_msg_sub
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transcation_msg_sub
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transcation_msg_sub
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transcation_msg_sub
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transcation_msg_sub
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transcation_msg_sub
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transcation_msg_sub
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_transcation_msg_sub
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMessageidIsNull() {
            addCriterion("messageId is null");
            return (Criteria) this;
        }

        public Criteria andMessageidIsNotNull() {
            addCriterion("messageId is not null");
            return (Criteria) this;
        }

        public Criteria andMessageidEqualTo(String value) {
            addCriterion("messageId =", value, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidNotEqualTo(String value) {
            addCriterion("messageId <>", value, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidGreaterThan(String value) {
            addCriterion("messageId >", value, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidGreaterThanOrEqualTo(String value) {
            addCriterion("messageId >=", value, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidLessThan(String value) {
            addCriterion("messageId <", value, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidLessThanOrEqualTo(String value) {
            addCriterion("messageId <=", value, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidLike(String value) {
            addCriterion("messageId like", value, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidNotLike(String value) {
            addCriterion("messageId not like", value, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidIn(List<String> values) {
            addCriterion("messageId in", values, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidNotIn(List<String> values) {
            addCriterion("messageId not in", values, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidBetween(String value1, String value2) {
            addCriterion("messageId between", value1, value2, "messageid");
            return (Criteria) this;
        }

        public Criteria andMessageidNotBetween(String value1, String value2) {
            addCriterion("messageId not between", value1, value2, "messageid");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andTopicidIsNull() {
            addCriterion("topicId is null");
            return (Criteria) this;
        }

        public Criteria andTopicidIsNotNull() {
            addCriterion("topicId is not null");
            return (Criteria) this;
        }

        public Criteria andTopicidEqualTo(String value) {
            addCriterion("topicId =", value, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidNotEqualTo(String value) {
            addCriterion("topicId <>", value, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidGreaterThan(String value) {
            addCriterion("topicId >", value, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidGreaterThanOrEqualTo(String value) {
            addCriterion("topicId >=", value, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidLessThan(String value) {
            addCriterion("topicId <", value, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidLessThanOrEqualTo(String value) {
            addCriterion("topicId <=", value, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidLike(String value) {
            addCriterion("topicId like", value, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidNotLike(String value) {
            addCriterion("topicId not like", value, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidIn(List<String> values) {
            addCriterion("topicId in", values, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidNotIn(List<String> values) {
            addCriterion("topicId not in", values, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidBetween(String value1, String value2) {
            addCriterion("topicId between", value1, value2, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidNotBetween(String value1, String value2) {
            addCriterion("topicId not between", value1, value2, "topicid");
            return (Criteria) this;
        }

        public Criteria andSubidIsNull() {
            addCriterion("subId is null");
            return (Criteria) this;
        }

        public Criteria andSubidIsNotNull() {
            addCriterion("subId is not null");
            return (Criteria) this;
        }

        public Criteria andSubidEqualTo(String value) {
            addCriterion("subId =", value, "subid");
            return (Criteria) this;
        }

        public Criteria andSubidNotEqualTo(String value) {
            addCriterion("subId <>", value, "subid");
            return (Criteria) this;
        }

        public Criteria andSubidGreaterThan(String value) {
            addCriterion("subId >", value, "subid");
            return (Criteria) this;
        }

        public Criteria andSubidGreaterThanOrEqualTo(String value) {
            addCriterion("subId >=", value, "subid");
            return (Criteria) this;
        }

        public Criteria andSubidLessThan(String value) {
            addCriterion("subId <", value, "subid");
            return (Criteria) this;
        }

        public Criteria andSubidLessThanOrEqualTo(String value) {
            addCriterion("subId <=", value, "subid");
            return (Criteria) this;
        }

        public Criteria andSubidLike(String value) {
            addCriterion("subId like", value, "subid");
            return (Criteria) this;
        }

        public Criteria andSubidNotLike(String value) {
            addCriterion("subId not like", value, "subid");
            return (Criteria) this;
        }

        public Criteria andSubidIn(List<String> values) {
            addCriterion("subId in", values, "subid");
            return (Criteria) this;
        }

        public Criteria andSubidNotIn(List<String> values) {
            addCriterion("subId not in", values, "subid");
            return (Criteria) this;
        }

        public Criteria andSubidBetween(String value1, String value2) {
            addCriterion("subId between", value1, value2, "subid");
            return (Criteria) this;
        }

        public Criteria andSubidNotBetween(String value1, String value2) {
            addCriterion("subId not between", value1, value2, "subid");
            return (Criteria) this;
        }

        public Criteria andMaxretryIsNull() {
            addCriterion("maxRetry is null");
            return (Criteria) this;
        }

        public Criteria andMaxretryIsNotNull() {
            addCriterion("maxRetry is not null");
            return (Criteria) this;
        }

        public Criteria andMaxretryEqualTo(Integer value) {
            addCriterion("maxRetry =", value, "maxretry");
            return (Criteria) this;
        }

        public Criteria andMaxretryNotEqualTo(Integer value) {
            addCriterion("maxRetry <>", value, "maxretry");
            return (Criteria) this;
        }

        public Criteria andMaxretryGreaterThan(Integer value) {
            addCriterion("maxRetry >", value, "maxretry");
            return (Criteria) this;
        }

        public Criteria andMaxretryGreaterThanOrEqualTo(Integer value) {
            addCriterion("maxRetry >=", value, "maxretry");
            return (Criteria) this;
        }

        public Criteria andMaxretryLessThan(Integer value) {
            addCriterion("maxRetry <", value, "maxretry");
            return (Criteria) this;
        }

        public Criteria andMaxretryLessThanOrEqualTo(Integer value) {
            addCriterion("maxRetry <=", value, "maxretry");
            return (Criteria) this;
        }

        public Criteria andMaxretryIn(List<Integer> values) {
            addCriterion("maxRetry in", values, "maxretry");
            return (Criteria) this;
        }

        public Criteria andMaxretryNotIn(List<Integer> values) {
            addCriterion("maxRetry not in", values, "maxretry");
            return (Criteria) this;
        }

        public Criteria andMaxretryBetween(Integer value1, Integer value2) {
            addCriterion("maxRetry between", value1, value2, "maxretry");
            return (Criteria) this;
        }

        public Criteria andMaxretryNotBetween(Integer value1, Integer value2) {
            addCriterion("maxRetry not between", value1, value2, "maxretry");
            return (Criteria) this;
        }

        public Criteria andRetryintervalIsNull() {
            addCriterion("retryInterval is null");
            return (Criteria) this;
        }

        public Criteria andRetryintervalIsNotNull() {
            addCriterion("retryInterval is not null");
            return (Criteria) this;
        }

        public Criteria andRetryintervalEqualTo(Integer value) {
            addCriterion("retryInterval =", value, "retryinterval");
            return (Criteria) this;
        }

        public Criteria andRetryintervalNotEqualTo(Integer value) {
            addCriterion("retryInterval <>", value, "retryinterval");
            return (Criteria) this;
        }

        public Criteria andRetryintervalGreaterThan(Integer value) {
            addCriterion("retryInterval >", value, "retryinterval");
            return (Criteria) this;
        }

        public Criteria andRetryintervalGreaterThanOrEqualTo(Integer value) {
            addCriterion("retryInterval >=", value, "retryinterval");
            return (Criteria) this;
        }

        public Criteria andRetryintervalLessThan(Integer value) {
            addCriterion("retryInterval <", value, "retryinterval");
            return (Criteria) this;
        }

        public Criteria andRetryintervalLessThanOrEqualTo(Integer value) {
            addCriterion("retryInterval <=", value, "retryinterval");
            return (Criteria) this;
        }

        public Criteria andRetryintervalIn(List<Integer> values) {
            addCriterion("retryInterval in", values, "retryinterval");
            return (Criteria) this;
        }

        public Criteria andRetryintervalNotIn(List<Integer> values) {
            addCriterion("retryInterval not in", values, "retryinterval");
            return (Criteria) this;
        }

        public Criteria andRetryintervalBetween(Integer value1, Integer value2) {
            addCriterion("retryInterval between", value1, value2, "retryinterval");
            return (Criteria) this;
        }

        public Criteria andRetryintervalNotBetween(Integer value1, Integer value2) {
            addCriterion("retryInterval not between", value1, value2, "retryinterval");
            return (Criteria) this;
        }

        public Criteria andRetryIsNull() {
            addCriterion("retry is null");
            return (Criteria) this;
        }

        public Criteria andRetryIsNotNull() {
            addCriterion("retry is not null");
            return (Criteria) this;
        }

        public Criteria andRetryEqualTo(Integer value) {
            addCriterion("retry =", value, "retry");
            return (Criteria) this;
        }

        public Criteria andRetryNotEqualTo(Integer value) {
            addCriterion("retry <>", value, "retry");
            return (Criteria) this;
        }

        public Criteria andRetryGreaterThan(Integer value) {
            addCriterion("retry >", value, "retry");
            return (Criteria) this;
        }

        public Criteria andRetryLessThanMaxRetry() {
            addCriterion("retry < maxRetry");
            return (Criteria) this;
        }

        public Criteria andRetryGreaterThanOrEqualTo(Integer value) {
            addCriterion("retry >=", value, "retry");
            return (Criteria) this;
        }

        public Criteria andRetryLessThan(Integer value) {
            addCriterion("retry <", value, "retry");
            return (Criteria) this;
        }

        public Criteria andRetryLessThanOrEqualTo(Integer value) {
            addCriterion("retry <=", value, "retry");
            return (Criteria) this;
        }

        public Criteria andRetryIn(List<Integer> values) {
            addCriterion("retry in", values, "retry");
            return (Criteria) this;
        }

        public Criteria andRetryNotIn(List<Integer> values) {
            addCriterion("retry not in", values, "retry");
            return (Criteria) this;
        }

        public Criteria andRetryBetween(Integer value1, Integer value2) {
            addCriterion("retry between", value1, value2, "retry");
            return (Criteria) this;
        }

        public Criteria andRetryNotBetween(Integer value1, Integer value2) {
            addCriterion("retry not between", value1, value2, "retry");
            return (Criteria) this;
        }

        public Criteria andNextretrytimeIsNull() {
            addCriterion("nextRetryTime is null");
            return (Criteria) this;
        }

        public Criteria andNextretrytimeIsNotNull() {
            addCriterion("nextRetryTime is not null");
            return (Criteria) this;
        }

        public Criteria andNextretrytimeEqualTo(Date value) {
            addCriterion("nextRetryTime =", value, "nextretrytime");
            return (Criteria) this;
        }

        public Criteria andNextretrytimeNotEqualTo(Date value) {
            addCriterion("nextRetryTime <>", value, "nextretrytime");
            return (Criteria) this;
        }

        public Criteria andNextretrytimeGreaterThan(Date value) {
            addCriterion("nextRetryTime >", value, "nextretrytime");
            return (Criteria) this;
        }

        public Criteria andNextretrytimeGreaterThanOrEqualTo(Date value) {
            addCriterion("nextRetryTime >=", value, "nextretrytime");
            return (Criteria) this;
        }

        public Criteria andNextretrytimeLessThan(Date value) {
            addCriterion("nextRetryTime <", value, "nextretrytime");
            return (Criteria) this;
        }

        public Criteria andNextretrytimeLessThanOrEqualTo(Date value) {
            addCriterion("nextRetryTime <=", value, "nextretrytime");
            return (Criteria) this;
        }

        public Criteria andNextretrytimeIn(List<Date> values) {
            addCriterion("nextRetryTime in", values, "nextretrytime");
            return (Criteria) this;
        }

        public Criteria andNextretrytimeNotIn(List<Date> values) {
            addCriterion("nextRetryTime not in", values, "nextretrytime");
            return (Criteria) this;
        }

        public Criteria andNextretrytimeBetween(Date value1, Date value2) {
            addCriterion("nextRetryTime between", value1, value2, "nextretrytime");
            return (Criteria) this;
        }

        public Criteria andNextretrytimeNotBetween(Date value1, Date value2) {
            addCriterion("nextRetryTime not between", value1, value2, "nextretrytime");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("version like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("version not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_transcation_msg_sub
     *
     * @mbggenerated do_not_delete_during_merge Mon Dec 25 10:55:07 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_transcation_msg_sub
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}