package com.liangbo.xing.flexibletranscation.domain.ftm;

import java.util.Date;

public class TranscationMsgDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transcation_msg.id
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transcation_msg.status
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transcation_msg.topicId
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    private String topicid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transcation_msg.pubId
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    private String pubid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transcation_msg.messageId
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    private String messageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transcation_msg.routingKey
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    private String routingkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transcation_msg.messageBody
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    private String messagebody;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transcation_msg.retry
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    private Integer retry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transcation_msg.nextRetryTime
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    private Date nextretrytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transcation_msg.version
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transcation_msg.createTime
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transcation_msg.updateTime
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transcation_msg.retryInterval
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    private Integer retryinterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transcation_msg.maxRetry
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    private Integer maxretry;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transcation_msg.id
     *
     * @return the value of t_transcation_msg.id
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transcation_msg.id
     *
     * @param id the value for t_transcation_msg.id
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transcation_msg.status
     *
     * @return the value of t_transcation_msg.status
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transcation_msg.status
     *
     * @param status the value for t_transcation_msg.status
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transcation_msg.topicId
     *
     * @return the value of t_transcation_msg.topicId
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public String getTopicid() {
        return topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transcation_msg.topicId
     *
     * @param topicid the value for t_transcation_msg.topicId
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void setTopicid(String topicid) {
        this.topicid = topicid == null ? null : topicid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transcation_msg.pubId
     *
     * @return the value of t_transcation_msg.pubId
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public String getPubid() {
        return pubid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transcation_msg.pubId
     *
     * @param pubid the value for t_transcation_msg.pubId
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void setPubid(String pubid) {
        this.pubid = pubid == null ? null : pubid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transcation_msg.messageId
     *
     * @return the value of t_transcation_msg.messageId
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public String getMessageid() {
        return messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transcation_msg.messageId
     *
     * @param messageid the value for t_transcation_msg.messageId
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void setMessageid(String messageid) {
        this.messageid = messageid == null ? null : messageid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transcation_msg.routingKey
     *
     * @return the value of t_transcation_msg.routingKey
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public String getRoutingkey() {
        return routingkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transcation_msg.routingKey
     *
     * @param routingkey the value for t_transcation_msg.routingKey
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void setRoutingkey(String routingkey) {
        this.routingkey = routingkey == null ? null : routingkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transcation_msg.messageBody
     *
     * @return the value of t_transcation_msg.messageBody
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public String getMessagebody() {
        return messagebody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transcation_msg.messageBody
     *
     * @param messagebody the value for t_transcation_msg.messageBody
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void setMessagebody(String messagebody) {
        this.messagebody = messagebody == null ? null : messagebody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transcation_msg.retry
     *
     * @return the value of t_transcation_msg.retry
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public Integer getRetry() {
        return retry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transcation_msg.retry
     *
     * @param retry the value for t_transcation_msg.retry
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void setRetry(Integer retry) {
        this.retry = retry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transcation_msg.nextRetryTime
     *
     * @return the value of t_transcation_msg.nextRetryTime
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public Date getNextretrytime() {
        return nextretrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transcation_msg.nextRetryTime
     *
     * @param nextretrytime the value for t_transcation_msg.nextRetryTime
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void setNextretrytime(Date nextretrytime) {
        this.nextretrytime = nextretrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transcation_msg.version
     *
     * @return the value of t_transcation_msg.version
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transcation_msg.version
     *
     * @param version the value for t_transcation_msg.version
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transcation_msg.createTime
     *
     * @return the value of t_transcation_msg.createTime
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transcation_msg.createTime
     *
     * @param createtime the value for t_transcation_msg.createTime
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transcation_msg.updateTime
     *
     * @return the value of t_transcation_msg.updateTime
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transcation_msg.updateTime
     *
     * @param updatetime the value for t_transcation_msg.updateTime
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transcation_msg.retryInterval
     *
     * @return the value of t_transcation_msg.retryInterval
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public Integer getRetryinterval() {
        return retryinterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transcation_msg.retryInterval
     *
     * @param retryinterval the value for t_transcation_msg.retryInterval
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void setRetryinterval(Integer retryinterval) {
        this.retryinterval = retryinterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transcation_msg.maxRetry
     *
     * @return the value of t_transcation_msg.maxRetry
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public Integer getMaxretry() {
        return maxretry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transcation_msg.maxRetry
     *
     * @param maxretry the value for t_transcation_msg.maxRetry
     *
     * @mbggenerated Mon Dec 25 10:55:07 CST 2017
     */
    public void setMaxretry(Integer maxretry) {
        this.maxretry = maxretry;
    }
}